# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/iconvmu/setup-devices.sh

PRODUCT_COPY_FILES += \
    /AndroidBoard.mk:system/AndroidBoard.mk \
    /AndroidProducts.mk:system/AndroidProducts.mk \
    /BoardConfig.mk:system/BoardConfig.mk \
    /BoardConfig.mk~:system/BoardConfig.mk~ \
    /cm.mk:system/cm.mk \
    /configs:system/configs \
    /configs/audio_effects.conf:system/configs/audio_effects.conf \
    /configs/audio_policy.conf:system/configs/audio_policy.conf \
    /configs/gps.conf:system/configs/gps.conf \
    /configs/media_profiles.xml:system/configs/media_profiles.xml \
    /configs/egl.cfg:system/configs/egl.cfg \
    /configs/thermald.conf:system/configs/thermald.conf \
    /configs/vold.fstab:system/configs/vold.fstab \
    /configs/OperatorPolicy.xml:system/configs/OperatorPolicy.xml \
    /configs/vold.conf:system/configs/vold.conf \
    /configs/UserPolicy.xml:system/configs/UserPolicy.xml \
    /configs/gps.xml:system/configs/gps.xml \
    /configs/wpa_supplicant.conf:system/configs/wpa_supplicant.conf \
    /device-copyfiles.txt:system/device-copyfiles.txt \
    /device_iconvmu.mk:system/device_iconvmu.mk \
    /extract-files.sh:system/extract-files.sh \
    /iconvmu-copyfiles.mk:system/iconvmu-copyfiles.mk \
    /icu:system/icu \
    /icu/icudt46l.dat:system/icu/icudt46l.dat \
    /idc:system/idc \
    /idc/qwerty2.idc:system/idc/qwerty2.idc \
    /idc/qwerty.idc:system/idc/qwerty.idc \
    /include:system/include \
    /kernel:system/kernel \
    /keychars:system/keychars \
    /keychars/surf_keypad.kcm:system/keychars/surf_keypad.kcm \
    /keychars/Virtual.kcm:system/keychars/Virtual.kcm \
    /keychars/Generic.kcm:system/keychars/Generic.kcm \
    /keychars/qwerty.kcm:system/keychars/qwerty.kcm \
    /keychars/qwerty2.kcm:system/keychars/qwerty2.kcm \
    /keylayout:system/keylayout \
    /keylayout/Vendor_046d_Product_c299.kl:system/keylayout/Vendor_046d_Product_c299.kl \
    /keylayout/qwerty.kl:system/keylayout/qwerty.kl \
    /keylayout/Vendor_05ac_Product_0239.kl:system/keylayout/Vendor_05ac_Product_0239.kl \
    /keylayout/Vendor_046d_Product_c216.kl:system/keylayout/Vendor_046d_Product_c216.kl \
    /keylayout/msm_tma300_ts.kl:system/keylayout/msm_tma300_ts.kl \
    /keylayout/Vendor_045e_Product_028e.kl:system/keylayout/Vendor_045e_Product_028e.kl \
    /keylayout/Vendor_046d_Product_c294.kl:system/keylayout/Vendor_046d_Product_c294.kl \
    /keylayout/surf_keypad.kl:system/keylayout/surf_keypad.kl \
    /keylayout/Vendor_046d_Product_c532.kl:system/keylayout/Vendor_046d_Product_c532.kl \
    /keylayout/sec_key.kl:system/keylayout/sec_key.kl \
    /keylayout/7k_handset.kl:system/keylayout/7k_handset.kl \
    /keylayout/Vendor_054c_Product_0268.kl:system/keylayout/Vendor_054c_Product_0268.kl \
    /keylayout/sec_touchkey.kl:system/keylayout/sec_touchkey.kl \
    /keylayout/sec_powerkey.kl:system/keylayout/sec_powerkey.kl \
    /keylayout/Vendor_04e8_Product_7021.kl:system/keylayout/Vendor_04e8_Product_7021.kl \
    /keylayout/AVRCP.kl:system/keylayout/AVRCP.kl \
    /keylayout/fluid-keypad.kl:system/keylayout/fluid-keypad.kl \
    /keylayout/Vendor_22b8_Product_093d.kl:system/keylayout/Vendor_22b8_Product_093d.kl \
    /keylayout/Generic.kl:system/keylayout/Generic.kl \
    /keylayout/icon-keypad.kl:system/keylayout/icon-keypad.kl \
    /keylayout/sii9234_rcp.kl:system/keylayout/sii9234_rcp.kl \
    /modules:system/modules \
    /proprietary-blobs.txt:system/proprietary-blobs.txt \
    /proprietary-files.sh:system/proprietary-files.sh \
    /recovery:system/recovery \
    /recovery/graphics.c:system/recovery/graphics.c \
    /recovery.fstab:system/recovery.fstab \
    /root:system/root \
    /root/init.target.rc:system/root/init.target.rc \
    /root/init.qcom.ril.path.sh:system/root/init.qcom.ril.path.sh \
    /root/lpm.rc:system/root/lpm.rc \
    /root/init.qcom.sh:system/root/init.qcom.sh \
    /root/fstab.qcom:system/root/fstab.qcom \
    /root/init.trace.rc:system/root/init.trace.rc \
    /root/init.rc:system/root/init.rc \
    /root/init.bt.rc:system/root/init.bt.rc \
    /root/init.qcom.lpm_boot.sh:system/root/init.qcom.lpm_boot.sh \
    /root/init.qcom.usb.rc:system/root/init.qcom.usb.rc \
    /root/init.qcom.usb.sh:system/root/init.qcom.usb.sh \
    /root/ueventd.rc:system/root/ueventd.rc \
    /root/init.qcom.rc:system/root/init.qcom.rc \
    /scripts:system/scripts \
    /scripts/init.qcom.efs.sync.sh:system/scripts/init.qcom.efs.sync.sh \
    /scripts/init.qcom.fm.sh:system/scripts/init.qcom.fm.sh \
    /scripts/init.qcom.sdio.sh:system/scripts/init.qcom.sdio.sh \
    /scripts/init.qcom.post_boot.sh:system/scripts/init.qcom.post_boot.sh \
    /scripts/init.qcom.wifi.sh:system/scripts/init.qcom.wifi.sh \
    /scripts/init.qcom.bt.sh:system/scripts/init.qcom.bt.sh \
    /scripts/init.qcom.coex.sh:system/scripts/init.qcom.coex.sh \
    /setup-devices.sh:system/setup-devices.sh \
    /setup-makefiles.sh:system/setup-makefiles.sh \
    /system.prop:system/system.prop \
    /vendorsetup.sh:system/vendorsetup.sh
